### ISSUE TITLE
-j for plants or fungi

### ISSUE THREAD

**Issue by xiekunwhy** [lh3/miniprot#15]
Hi @lh3 ,

1) can I always using -j 2 for animals?
2) is there an optimized -j value for plants and fungi?
3) would you please add some more species to evaluation table, especially plants?

Best,
Kun

**Comment by lh3** [comment]
-j2 should be good for birds, perhaps for vertebrate, too, but definitely not for all metazoan. Use -j1 for plants and fungi. I might make -j1 the default in the v0.5 release.
