### ISSUE TITLE
Splice model

### ISSUE THREAD

**Issue by arunvv90** [lh3/miniprot#16]
Hi,
Thank you for the great tool!! I am using it for virus annotation(Ictalurid herpesvirus). Testing went very well. In the last update, two splice models are added. In the earlier version, I was using the default version. I was wondering which model would be appropriate for my case(I guess the general model?). Another question is about the GFF format. My GFF looks like this
C02-169_draft1	miniprot	mRNA	33598	35094	2600	+	.	ID=C02-169_ORF25_000001;Identity=0.9940;Positive=0.9960;Target=C02-169_ORF25 1 498
Can you please tell me what is 2600, Identity(nucleotide identity or amino acid identity), Positive=0.9960, and the last two columns(1,498)? Please forgive me for these silly questions from a newcomer. There are not many good tools out there for virus annotation and most of them fail with introns like herpesvirus. Your tool seems very promising.

**Comment by lh3** [comment]
I don't know what splice site look like in Ictalurid herpesvirus (is it GT-AG?). It is safer to use -j1, which is now the default and is equivalent to the splice model in v0.4.

> nucleotide identity or amino acid identity

Amino acid. miniprot doesn't see the nucleotide sequences of query genes.

> the last two columns

See the GFF3 spec. It is the region of the query protein aligned

**Comment by arunvv90** [comment]
Thank you for the quick reply. Splice junctions in the virus are major GT-AG or minor AT-AC

**Comment by lh3** [comment]
Thanks. I didn't know that. Miniprot considers GT-AG, GC-AG and AT-AC. I think it should work.
