### ISSUE TITLE
out-of-memory error

### ISSUE THREAD

**Issue by rwhetten** [lh3/miniprot#25]
I pulled the latest version from the repository and compiled with gcc v10.2.0 on a node with 384 Gb RAM and SSE2 instruction set, but the program is killed by the oom-killer after less than 1 minute of run time trying to build an index of hg38. Monitoring the top command in an interactive session never shows >5 gb memory use. The command used was
`miniprot -t10 -d hg38.mpi hg38.fa` and the command line output was
```
[M::mp_ntseq_read@9.319*1.00] read 3221011060 bases in 493 contigs
[M::mp_idx_build@9.319*1.00] 25164620 blocks
Killed
```
Is there some aspect of node architecture or configuration that could cause this?

**Comment by lh3** [comment]
Cluster nodes typically cap the max memory unless you change it.
