### ISSUE TITLE
deletion in GFF output

### ISSUE THREAD

**Issue by YoshiKawahara** [lh3/miniprot#29]
Hi,
Thanks for the great tool. Deletion in the alignment (CIGAR) is not reflected in the GFF output. I would like to have the option to include Deletion in the GFF, although it is indistinguishable from introns.

Thanks in advance.

**Comment by lh3** [comment]
> Deletion in the alignment (CIGAR) is not reflected in the GFF output.

GFF is not meant to encode all information. Please parse the CIGAR.

> it is indistinguishable from introns

Deletions and introns are treated differently.
