### ISSUE TITLE
typo on the man page?

### ISSUE THREAD

**Issue by azat-badretdin** [lh3/miniprot#31]
https://lh3.github.io/miniprot/miniprot.html

nU	Phase-1 intron. Consuming n nucleotides and 1 amino acid
nV	Phase-2 intron. Consuming n nucleotides and 1 amino acid

Same description.

**Comment by lh3** [comment]
This is not a typo. The difference is "Phase-1" vs "Phase-2". Actually as I am thinking now, we can probably merge the two operators.

**Comment by azat-badretdin** [comment]
I think I misunderstood the description in  a way that the comment is describing the nature of the phase while in fact the description of what is Phase-1 and -2 is elsewhere.
