### ISSUE TITLE
Very large number of large introns for a plant genome

### ISSUE THREAD

**Issue by kkrizanovic** [lh3/miniprot#32]
Hello, 

I've been using miniprot to map a set of refseq proteins to an assembled plant genome.

I've been using the result gff file for gene prediction (together with other data). However, I get a lot of very large introns, over 10kbp. A biologist colleague informs me that in other published studies, this number is much lower.

Do you have any advice on how to improve miniprot output? I could set the maximum intron size, but can you maybe suggest changing some other options.

**Comment by lh3** [comment]
The default of miniprot is tuned for the human genome. For small genomes, it is recommended to set the max intron size to a smaller number with `-G`. The miniprot paper did this for the Drosophila dataset.

Spaln2 adjusts the max intron size automatically based on the genome size. I am considering to add a similar feature but it won't be implemented soon.

**Comment by lh3** [comment]
I have just released v0.8 with a new option `-I` to automatically set the max intron size based on the genome size. Nonetheless, you may still want to use `-G` to explicitly set the max intron size as you know your genome better.
