### ISSUE TITLE
Filter by alignment quality

### ISSUE THREAD

**Issue by stubrown** [lh3/miniprot#42]
A protein to DNA alignment with translated BLAST can be filtered by e-value so the output  only contains matches above a specified e-value.  miniprot has an alignment score (sort of similar to Smith-Waterman) and a Mapping score (sort of similar to Bowtie).  Can you add a command line parameter to filter output by a minimum quality so the gff can be used directly, for example as a JBrowse track.

**Comment by lh3** [comment]
It is difficult to filter when you look at a single protein. Miniprot is intended for aligning similar proteins (say, identity >50%). The E-value is usually small. Alignment score is roughly proportional to the protein length. We can't easily set a cut off on that score. Mapping quality evaluates whether an alignment is unique. It is not that useful for protein alignment as we expect multi-gene families.
