### ISSUE TITLE
'Killed' message from index build

### ISSUE THREAD

**Issue by crowja** [lh3/miniprot#44]
Building a `miniprot` index for maize fails with a 'Killed' message:
```
$ miniprot -t 4 -d test.mpi ../test.fa
[M::mp_ntseq_read@13.628*0.51] read 2176935545 bases in 13 contigs
[M::mp_idx_build@13.628*0.51] 17007324 blocks
[M::mp_idx_build@50.757*2.97] collected syncmers
Killed
$ echo $?
137
```
Any thoughts on how to proceed? Possibly a tmp file thing?

**Comment by crowja** [comment]
Yep, that was the issue. I doubled the memory and the indexing proceeds nicely. Thanks!

**Comment by lh3** [comment]
Just FYI: indexing usually takes more memory than alignment
