### ISSUE TITLE
A way to prefer closer exons in tandemly duplicated genes on the same strand

### ISSUE THREAD

**Issue by melop** [lh3/miniprot#53]
I think this is related to a known issue. When we are dealing with tandemly duplicated genes on the same strand, miniprot could prefer more distant exons instead of the ones closer. The phenomenon can be visualized below:
![image](https://github.com/lh3/miniprot/assets/1661121/12078de3-f5f3-460b-9a4f-271db612323b)

Some long introns would result in this case. I'm thinking, is it possible to give penalties to intron length, so that miniprot would prefer the alignment with the closest exons?

Ray

**Comment by lh3** [comment]
You may increase `-w` to adjust the gap penalty during chaining.
