### ISSUE TITLE
Different translation tables

### ISSUE THREAD

**Issue by giacomomutti** [lh3/miniprot#57]
Hello! 
I was wondering if it would be possible to add a feature to miniprot to use different non-standard genetic codes to use during the translation of the reference genome step. It would be extremely useful to annotate genes in certain lineages

Thank you very much for the amazing tool!

**Comment by lh3** [comment]
The github HEAD now supports NCBI translation table 1 through 5. If you need rarer tables, let me know.

**Comment by giacomomutti** [comment]
Thank you very much for the quick implemenation! 

I would need rarer tables as I am studying ciliates genome (for example, tables 27, 29 and 30). I transformed all [ncbi genetic tables](https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi) in the format used in nasw-tab.c (AAA,AAC... order) in case it may be useful. However, some indexes are not present (like 7, 8, 17 to 20) and I guessed this would need to be handled in the code somehow but I don't know how to program in C to do a pull request. I hope this is useful and thanks again!

`
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVVQYQYSSSS*CWCLFLFX", // 6: Ciliate Nuclear; Dasycladacean Nuclear; Hexamita Nuclear
   "NNKNTTTTSSSSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSWCWCLFLFX", // 9: Echinoderm Mitochondrial; Flatworm Mitochondrial
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSCCWCLFLFX", // 10: Euplotid Nuclear
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSS*CWCLFLFX", // 11: Bacterial, Archaeal and Plant Plastid
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLSLEDEDAAAAGGGGVVVV*Y*YSSSS*CWCLFLFX", // 12: Alternative Yeast Nuclear
   "KNKNTTTTGSGSMIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSWCWCLFLFX", // 13: Ascidian Mitochondrial
   "NNKNTTTTSSSSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVVYY*YSSSSWCWCLFLFX", // 14: Alternative Flatworm Mitochondrial
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*YQYSSSS*CWCLFLFX", // 15: Blepharisma Macronuclear
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*YLYSSSS*CWCLFLFX", // 16: Chlorophycean Mitochondrial
   "NNKNTTTTSSSSMIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSWCWCLFLFX", // 21: Trematode Mitochondrial
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*YLY*SSS*CWCLFLFX", // 22: Scenedesmus obliquus Mitochondrial
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSS*CWC*FLFX", // 23: Thraustochytrium Mitochondrial
   "KNKNTTTTSSKSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSWCWCLFLFX", // 24: Rhabdopleuridae Mitochondrial
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSGCWCLFLFX", // 25: Candidate Division SR1 and Gracilibacteria
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLALEDEDAAAAGGGGVVVV*Y*YSSSS*CWCLFLFX", // 26: Pachysolen tannophilus Nuclear
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVVQYQYSSSSWCWCLFLFX", // 27: Karyorelict Nuclear
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVVQYQYSSSSWCWCLFLFX", // 28: Condylostoma Nuclear
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVVYYYYSSSS*CWCLFLFX", // 29: Mesodinium Nuclear
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVVEYEYSSSS*CWCLFLFX", // 30: Peritrich Nuclear
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVVEYEYSSSSWCWCLFLFX", // 31: Blastocrithidia Nuclear
   "KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*YWYSSSS*CWCLFLFX", // 32: Balanophoraceae Plastid
   "KNKNTTTTSSKSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVVYY*YSSSSWCWCLFLFX", // 33: Cephalodiscidae Mitochondrial
`

**Comment by lh3** [comment]
Added. Thank you so much!

**Comment by giacomomutti** [comment]
Wow, thank you so much again for the speed. However there is one slight issue. If you use -T 6 it says "[ERROR] failed to find translation table 6" but it should be there.  The same happens for -T 33. I guess there is a problem with indexing (it seems that to use table 6 you need to input -T 5). Indeed if you run -T 8 (which should return error), it works, I guess using table 9.

**Comment by lh3** [comment]
That is a bug. Now fixed. Thanks!

**Comment by lh3** [comment]
it should be there
