### ISSUE TITLE
Add an option to not to print ##PAF line to gff file

### ISSUE THREAD

**Issue by xiekunwhy** [lh3/miniprot#6]
Hi,

1) Would you please add an option to not to print ##PAF line to gff file? Those lines may cause some errors when using gffread(https://github.com/gpertea/gffread) to do some downstream screening.
gffread Opl.gff -T -o Opl.gtf
![image](https://user-images.githubusercontent.com/17738229/190091110-8af73f7e-ecfa-4dfa-a5bf-45c4dc4f401b.png)

2) The ID prefix now is MP, would please add an option to accept custom ID prefix (and accept custom source name if possible) ? We have difference protein sets with differece weight need to mapping some times, for example, preparing homolog annotation results for evm (https://evidencemodeler.github.io/).

Best,
Kun

**Comment by lh3** [comment]
1. Will add an option to disable `##PAF` lines. For now, use `grep -v ^##PAF` to postprocess the output.
2. I also want to have an option to change the prefix. It just hasn't been implemented yet. As you mention it, I will implement this feature soon.

**Comment by lh3** [comment]
1. Use `--gff-only`
2. Use `-P MyPrefix`
