### ISSUE TITLE
Allow to index ORFs from the beginning

### ISSUE THREAD

**Issue by jfouret** [lh3/miniprot#66]
Thank you for this tool.

From my tests I concluded that ORFs are indexed based on a start codon (even without stop codon when reaching the end of a contig)

When an ORF is split in 2 contigs, this prevents the identification of the the second part while we can identify the first part of a mapping at the end of one contig.

You could add an option to automatically consider 3 ORF from position 1, 2 and 3 (1-based) of each input reference to index (optional and default to false). This would make it possible to identify a mapping across 2 contigs.

Bests,

**Comment by lh3** [comment]
A spliced exon doesn't have a start codon, and so at the indexing step, miniprot doesn't look for start codons, either. For split alignment, you will probably want to reduce `--outs`. I will change the behavior of this option in the next release.

**Comment by jfouret** [comment]
yes my bad. I used `--outs 0.4` but the way it was split I needed to use even a lower value.

Thx,
